
function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		if gui.pick_node(gui.get_node("play_button"), action.x, action.y) then
			msg.post("game_controller:/gc#game_controller", "load_level", {
				level = hash("game")
			})
		elseif gui.pick_node(gui.get_node("quit_button"), action.x, action.y) then
			msg.post("@system:", "exit", {
				code = 0
			})
		end
	end
end
